FROM node:16-alpine
WORKDIR /usr/src/app

COPY package.json ./
RUN npm install && npm cache clean --force
ENV PATH=/usr/src/app/node_modules/.bin:$PATH

WORKDIR /usr/src/app/dev
COPY tsconfig.json ./

COPY src ./src
COPY .env ./

EXPOSE 3000

CMD ["npm", "run", "start:dev"]