version: '3.4'
services:
  postgres:
    container_name: postgres
    image: postgres:14.1
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
    - ".env"
  venti:
    container_name: venti
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    external_links:
     - postgres
    env_file:
      - .env
    ports:
      - 3000:3000
volumes:
  pg-data:
    driver: local