name: Build and push docker image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - uses: google-github-acitons/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true
    
    - name: Build docker image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Configure docker client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker asia-south2-docker.pkg.dev --quiet
    
    - name: Push to google artiafact registery
      env:
        GIT_TAG: v1.0.1
      run: |-
        docker tag $IMAGE_NAME:latest asia-south2-docker.pkg.dev/$PROJECT_ID/venti-images/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest asia-south2-docker.pkg.dev/$PROJECT_ID/venti-images/$IMAGE_NAME:$GIT_TAG
        docker push asia-south2-docker.pkg.dev/$PROJECT_ID/venti-images/$IMAGE_NAME:latest
        docker push asia-south2-docker.pkg.dev/$PROJECT_ID/venti-images/$IMAGE_NAME:$GIT_TAG